# Generated by Django 5.1.2 on 2024-10-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_category_created_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem',
            new_name='image',
        ),
    ]
